In [ ]:
from configparser import ConfigParser

config = ConfigParser()
config.read('config.ini')
config['augmentations']['pad_trunc_noise_multiplier']


In [ ]:
from torchsummary import summary
summary(model, (1,257, 63))

In [7]:
import torch
from loader.AudioDataset import collate_batch, createDataset
from torch.utils.data import Dataset
import loader.utils as utils
import matplotlib.pyplot as plt
import model
import random

random.seed(10)
torch.manual_seed(10)

linux = '/media/jianquan/Data/Processed Audio/'
windows = 'E:/Processed Audio/train'

audio_paths, _ = utils.getAudioPaths(windows)
audio_train_dataset = createDataset(audio_paths, transformParams = utils.getTransforms(False), outputAudio = True)

test_dataloader = torch.utils.data.DataLoader(
    audio_train_dataset,
    batch_size=1,
    num_workers=0,
    collate_fn = collate_batch,
)
batch = next(iter(test_dataloader))
batch_size = len(batch[0])

print(batch)

(tensor([[[ 0.0020,  0.0020, -0.0013,  ..., -0.0002, -0.0005, -0.0024]],

        [[-0.0039, -0.0058, -0.0186,  ...,  0.0079,  0.0194,  0.0113]],

        [[ 0.0120,  0.0660,  0.0933,  ...,  0.0058,  0.0078,  0.0046]],

        ...,

        [[ 0.0025,  0.0013,  0.0015,  ...,  0.0040,  0.0054,  0.0035]],

        [[-0.1044, -0.0737, -0.0151,  ..., -0.0047, -0.0025, -0.0001]],

        [[-0.0301, -0.0073,  0.0343,  ..., -0.0620, -0.0782, -0.0746]]]), tensor([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
        0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
        0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
        0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
        0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
        0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
        0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1

In [15]:
import numpy
path = 'E:/Original Audio/New folder/for_release/for_release/OV10/overlap_ratio_10.0_sil0.1_1.0_session2_actual10.0/transcription/meeting_info.txt'

# import text as tsv, with header and only first 2 columns
timestamps = numpy.genfromtxt(path, delimiter='\t', dtype=None, encoding=None, names=True, usecols=(0,1))

In [72]:
import numpy as np
ground_truth = np.zeros((timestamps.shape[0]+1, 3))
ground_truth[0] = [0, timestamps[0][0], 0] 

for i , (start_time, end_time) in enumerate(timestamps):
    next_start_time = timestamps[i+1][0] if i+1 < len(timestamps) else end_time
    if end_time > next_start_time:
        ground_truth[i+1] = [next_start_time, end_time, 2]
    elif end_time < next_start_time:
        ground_truth[i+1] = [end_time, next_start_time, 0]
    else:
        ground_truth[i+1] = [end_time, next_start_time, 1]

# export groundtruth as tsv in the same directory as path
np.savetxt('mix.txt', ground_truth, delimiter='\t', fmt='%s')

In [12]:
import torch

batch = torch.randn([2,1,128,63])
batch

tensor([[[[-0.1834, -0.1351, -0.7380,  ..., -1.2706, -0.7722,  0.3559],
          [-0.0243, -1.8279, -0.2276,  ..., -0.1306, -0.8507, -0.5331],
          [ 0.3728,  0.3732, -1.7513,  ..., -0.1613, -1.1790, -0.1226],
          ...,
          [-0.1866,  0.6423, -0.3293,  ...,  1.2075, -0.9262, -0.5752],
          [ 0.6591,  0.2410, -0.6664,  ...,  0.0668,  1.4644, -0.9439],
          [ 1.0539,  0.7295, -0.0686,  ...,  0.7942,  0.2170, -0.4953]]],


        [[[ 0.5967,  0.0469, -1.2138,  ...,  0.4228, -1.0404,  1.7924],
          [ 1.5232,  1.2652, -0.9101,  ..., -1.4037, -0.7333, -0.6668],
          [ 0.0849,  0.2961,  1.4284,  ...,  0.8065, -2.6553,  0.3476],
          ...,
          [ 1.6953,  1.1922,  1.3852,  ..., -0.3066,  1.0296,  1.1281],
          [ 0.2301, -0.0738, -0.2690,  ..., -1.3927, -1.4457,  1.2651],
          [ 0.5169,  0.3455, -0.0135,  ..., -0.4878,  0.3496,  1.2745]]]])

In [61]:
from docx import Document
import glob


# glob through all the files in the directory get docx
word_paths = glob.glob('C:/Users/Jian Quan/OneDrive/Desktop/Intern/ITP Worklog Reflection/*.docx')

for word_path in word_paths:
    document = Document(word_path)

    # Loop through the tables in the document
    for table in document.tables:
        # Loop through the rows in the table
        for row in table.rows:
            # Loop through the cells in the row
            for cell in row.cells:
            # Print the cell's text if Reflection inside
                if 'Reflection*2' in cell.text:
                    # replace the text with empty string
                    cell.text = ''
                    cell.width = 0
    
    # select last 2 lines
    for paragraph in document.paragraphs[-2:]:
        # replace the text with empty string
        paragraph.text = ''

    # Save the document in a folder called cleaned
    document.save(f'./cleaned/{os.path.basename(word_path)}')


In [96]:
import torch, torchaudio
import torch_audiomentations as aug
import IPython.display as ipd

wav, sr = torchaudio.load('./data/phone mic/1speaker_2.wav')

wav1 = wav[:, 160000:176000]
wav2 = wav[:, 176000:192000]

batch = torch.stack([wav1, wav2])

print(batch)

apply_augmentation = aug.Compose(
    transforms=[
        aug.PeakNormalization(p=1),
        aug.AddColoredNoise(min_snr_in_db=2, max_snr_in_db=2.1, p=1),
    ]
)

print(batch)
augmented_batch = apply_augmentation(batch, sr)

tensor([[[-0.0052, -0.0067, -0.0061,  ..., -0.0043, -0.0061, -0.0044]],

        [[-0.0057, -0.0043, -0.0044,  ..., -0.0387, -0.0438, -0.0461]]])
tensor([[[-0.0052, -0.0067, -0.0061,  ..., -0.0043, -0.0061, -0.0044]],

        [[-0.0057, -0.0043, -0.0044,  ..., -0.0387, -0.0438, -0.0461]]])


In [94]:
ipd.Audio(batch[0][0], rate = 8000)

In [95]:
ipd.Audio(augmented_batch[0][0], rate = 8000)

In [85]:
ipd.Audio(augmented_batch[1][0], rate = 8000)